### ISSUE TITLE
Bad date in OCS

### ISSUE THREAD

**Issue by Tazzmaniack** [PluginsOCSInventory-NG/winupdate#6]
I have installed the last package in /usr/share/ocsinventory-reports/ocsreports/download/ redhat 7.x with last version of OCS 2.5. and put the vbs on each agent in plugins directory with good rights. But when i tried to see the date of installation KB i see : 0000-00-00 00:00:00 in installation date. but on the xml file : i see for example :
       <SOFTWARES>
            <PUBLISHER>Microsoft Corporation</PUBLISHER>
            <NAME>Update KB2919355</NAME>
            <VERSION />
            <FOLDER />
            <COMMENTS>(http://support.microsoft.com/?kbid=2919355)</COMMENTS>
            <FILENAME />
            <FILESIZE>0</FILESIZE>
            <GUID />
            <LANGUAGE />
            <INSTALLDATE>11/22/2014</INSTALLDATE>
            <BITSWIDTH>0</BITSWIDTH>
            <SOURCE>0</SOURCE>
        </SOFTWARES>

Why the date is on french state and not us ? this is perhaps why we don't have the date on OCS ?

**Comment by Tazzmaniack** [comment]
Thanks in advance to help me

**Comment by charleneauger** [comment]
Hi @Tazzmaniack ,

The windows update date format is mm/dd/YYYY and not dd/mm/YYYY. 

This is a weird behavior from windows itself because the software installation date will always be returned in the YYYY/mm/dd.
However, the windows KB and patches will always have the mm/dd/YYYY format.

If you plan on getting an accurate installation date, we recommend to install the latest version of the plugin.
We also added the hotfix so it will return a more detailled list of applied patches on the computer.

Regards,
Charlene
